### ISSUE TITLE
Stopping ECS agent takes ~3-4 minutes

### ISSUE THREAD

**Issue by Trane9991** [aws/amazon-ecs-init#88] opened 2017-04-20 13:17 UTC
Hello, 
I'm running latest MultiContainer Elastic Beanstalk environment.

I'm trying to increase "ECS_CONTAINER_STOP_TIMEOUT".
I have pre-deployment hook, wich modifies "ecs.config" file and restarting ECS agent.

But I faced the issue that command "initctl stop ecs" being executed ~3-4 minutes, which makes my deployment process 2x longer.

Is it possible, to reread configurations without restarting ECS agent, or is there faster and safe way to do that?

**Comment by Trane9991** [comment] 2017-04-20 13:24
Here is log:
```
2017-04-20T13:15:57Z [INFO] pre-stop
2017-04-20T13:15:57Z [INFO] Stopping Amazon EC2 Container Service Agent
2017-04-20T13:15:57Z [INFO] Container name: /ecs-awseb-...-a6bca991cd9393ec2300
2017-04-20T13:15:57Z [INFO] Container name: /ecs-awseb-...-c886988bf8a3f6873600
2017-04-20T13:15:57Z [INFO] Container name: /ecs-agent
2017-04-20T13:15:57Z [INFO] Agent exited with code 0
2017-04-20T13:18:58Z [INFO] post-stop
2017-04-20T13:18:58Z [INFO] Cleaning up the credentials endpoint setup for Amazon EC2 Container Service Agent
2017-04-20T13:18:58Z [INFO] pre-start
2017-04-20T13:18:58Z [INFO] start
2017-04-20T13:18:58Z [INFO] Container name: /ecs-awseb-...-a6bca991cd9393ec2300
2017-04-20T13:18:58Z [INFO] Container name: /ecs-awseb-...-c886988bf8a3f6873600
2017-04-20T13:18:58Z [INFO] Container name: /ecs-agent
2017-04-20T13:18:58Z [INFO] Removing existing agent container ID: 5b4e4b91d5e65c6ef387874f5e6a325cea34286370532e1badc8d9d9d4297370
2017-04-20T13:18:58Z [INFO] Starting Amazon EC2 Container Service Agent
```

**Comment by aaithal** [comment] 2017-04-25 22:41
Hi @Trane9991, thanks for reporting this.

> Is it possible, to reread configurations without restarting ECS agent,

Unfortunately, the only way to do this today requires restarting the ECS Agent. 

> Looks like "post-stop" being launched only after 3 minutes.

I was able to reproduce this in my multicontainter beanstalk setup as well. However, I was unable to reproduce the same issue on an instance that's running the latest ECS Optimized AMI.

It doesn't seem to be because of any delays in `ecs-init` itself. As you can see from the output below, it seems to be to related to the `eb-ecs` upstart job:

###### Stop Duration with `eb-ecs` upstart job:
* Stop `ecs` service
```bash
$ initctl status ecs
initctl status ecs
ecs start/running, process 4742

$ time initctl stop ecs
ecs stop/waiting

real	3m1.751s
user	0m0.000s
sys	0m0.000s
```

###### Stop Duration without `eb-ecs` upstart job:
* Remove the upstart job:
```
$ mv /etc/init/eb-ecs.conf /home/ec2-user
$ reboot
```
* Stop `ecs` service
```bash
$ initctl status ecs
initctl status ecs
ecs start/running, process 926

$ time initctl stop ecs
ecs stop/waiting

real	0m0.122s
user	0m0.000s
sys	0m0.000s
```

Can you please reach out to the Elastic Beanstalk team via AWS Developer Support or [AWS Forums](forums.aws.amazon.com) to get a remediation for this issue? 

I'm closing this issue as there aren't any action items for the ECS Init itself. Please feel free to add more comments, re-open the issue if you run into anything else.

Thanks,
Anirudh

**Closed by aaithal** 2017-04-25 22:41 UTC
