### ISSUE TITLE
Make supervisor more error tolerant

### ISSUE THREAD

**Issue by 2opremio** [aws/amazon-ecs-init#29] opened 2015-10-07 19:32 UTC
`amazon-ecs-init start` doesn't tolerate errors in the client or in docker since it simply exits whenever an error occurs instead of retrying: 

https://github.com/aws/amazon-ecs-init/blob/cbf60dad55e0d301bbdc9168bd893750bc336190/ecs-init/engine/engine.go#L121

I have run into docker bugs such us https://github.com/docker/docker/issues/14738 which have resulted in ecs-agent not starting at all in my instances.

I would propose to either:
- Add configurable retries for `amazon-ecs-init start`
- Use [Upstart's `respawn`](http://upstart.ubuntu.com/cookbook/#respawn)

**Comment by samuelkarp** [comment] 2015-10-07 19:41
Thanks for the suggestion!  Do you know if the errors you're experiencing are transient (i.e., a retry would resolve the issue) or are more permanent (e.g., they'll reoccur until the Docker daemon is restarted or until the host is rebooted, etc)?

**Comment by 2opremio** [comment] 2015-10-07 19:47
The ones I have run into are mostly transient, due to docker not being able to start the container for whatever reason, docker/docker#14738 for instance.

However, I have also run into other problems due to the Go Docker client being picky about persistent connections. See https://github.com/weaveworks/weave/issues/1514 and https://github.com/weaveworks/weave/issues/1103

**Comment by samuelkarp** [comment] 2015-10-07 19:56
Thanks, that helps.  ecs-init is using a somewhat old version of go-dockerclient and I'd like to first try updating the dependencies to see if we can avoid those problems in the first place (https://github.com/fsouza/go-dockerclient/issues/281 looks potentially related to the persistent connections issue you've experienced).

**Comment by samuelkarp** [comment] 2015-10-07 20:00
@2opremio I've just opened https://github.com/aws/amazon-ecs-init/pull/30 to update the dependencies.  Do you mind trying it out to see if it helps?

**Comment by 2opremio** [comment] 2015-10-07 23:23
@samuelkarp Will do (probably not before next week though). However, I am not too hopeful since the HTTP glitches we have found don't surface with the Docker daemon.

**Comment by samuelkarp** [comment] 2017-02-07 19:54
Just a note here: we've improved the resilience of ecs-init to failures related to Docker starting slowly, released in [v1.14.0-2](https://github.com/aws/amazon-ecs-init/releases/tag/v1.14.0-2).

**Comment by 2opremio** [comment] 2017-02-07 20:00
Great, thanks for the update.

**Comment by matwood** [comment] 2017-04-26 18:57
I'm using the latest ECS optimized AMI (amzn-ami-2016.09.g-amazon-ecs-optimized) on an m4.large. When adding a new instance to the cluster it will randomly fail to start the agent. If I log into the instance and start the agent manually it works. I'm seeing these errors in the init log which lead me to believe it is tied to a long docker start up 
```
2017-04-26T15:12:04Z [INFO] Network error connecting to docker, backing off for '1.14777941s', error: dial unix /var/run/docker.sock: connect: no such file or directory
2017-04-26T15:12:06Z [INFO] Network error connecting to docker, backing off for '2.282153551s', error: dial unix /var/run/docker.sock: connect: no such file or directory
2017-04-26T15:12:08Z [INFO] Network error connecting to docker, backing off for '4.466145821s', error: dial unix /var/run/docker.sock: connect: no such file or directory
2017-04-26T15:12:12Z [INFO] Network error connecting to docker, backing off for '5.235010051s', error: dial unix /var/run/docker.sock: connect: no such file or directory
2017-04-26T15:12:18Z [INFO] Network error connecting to docker, backing off for '5.287113937s', error: dial unix /var/run/docker.sock: connect: no such file or directory
2017-04-26T15:12:23Z [ERROR] dial unix /var/run/docker.sock: connect: no such file or directory
```
Can the init be configured to keep trying for a longer period of time? Any other ideas?

**Comment by cyastella** [comment] 2020-01-09 19:15
Hi: 
@matwood, sorry for the delay response.  
For your question, we currently allow maxRetries here.[https://github.com/aws/amazon-ecs-init/blob/7216f783b7dbf3e0641c554a6b2091fb9c5aec59/ecs-init/docker/docker.go#L121]().

**Comment by cyastella** [comment] 2020-01-13 18:58
This is by design, close it for now. We will revisit this feature request when we there's enough demand for it. Feel free to reopen it when you have new concerns and issues. Thanks a lot!

**Closed by cyastella** 2020-01-13 18:58 UTC
Labels: kind/enhancement
